<?php
session_start();

require_once "../../../controllers/clientsingle.controller.php";
require_once "../../../models/clientsingle.model.php";

class printClients{
public function getClientsPrinting(){ 
  $clients = (new ControllerClient)->ctrShowClientList();

  require_once('tcpdf_include.php');
  $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
  $pdf->startPageGroup();
  $pdf->setPrintHeader(false);

  $pdf->AddPage();
    $header = <<<EOF
    <table>
      <tr>
        <td style="width:540px;text-align:center;font-size:1.2em;font-weight:bold;">INTPROG CORPORATION</td> 
      </tr>

      <tr>
        <td style="width:540px;text-align:center;font-size:10px;">Bacolod City</td> 
      </tr>  

      <tr>
        <td style="width:540px;text-align:center;font-size:1.2em;font-weight:bold;">CLIENT LISTING</td> 
      </tr>   

      <tr>
        <td></td>
      </tr>

      <tr>
        <td style="width:25px;"></td>

        <td style="border: 1px solid #666;width:245px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp;Client Name</td>
                                                            
        <td style="border: 1px solid #680;width:255px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp;Address</td>              
      </tr>                        
    </table>
EOF;
    $pdf->writeHTML($header, false, false, false, false, '');

// ------------------------------------------------------------
  foreach ($clients as $key => $value) {
    $cname = $value["cname"];
    $address = $value["address"];
    $contact = $value["phone"] . ', ' . $value["mobile"];
   
      $content = <<<EOF
      <table>    
        <tr>
          <td style="width:25px;"></td>        

          <td style="width:250px;text-align:left;font-size:11px;">$cname</td>                                                             
           <td style="width:265px;text-align:left;font-size:11px;">$address</td>                  
        </tr>                
      </table>
EOF;
      $pdf->writeHTML($content, false, false, false, false, '');
    }

  $footer = <<<EOF
    <table style="border: none;">    
      <tr>
        <td></td>
      </tr>
      <tr>  
        <td style="width:505px;text-align:right;font-size:8px;">Generated by</td>
      </tr> 
      <tr>  
        <td style="width:505px;text-align:right;font-size:10px;"></td>
      </tr>                              
    </table>
EOF;
      $pdf->writeHTML($footer, false, false, false, false, '');     

    $pdf->Output('client_list.pdf', 'I');
   }
  }  

  $clientsForm = new printClients();
  $clientsForm -> getClientsPrinting();
?>